# 1) CI sur branch1 uniquement
trigger:
  branches:
    include:
      - Branch_one

# 2) Validation PR vers main
pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      flake8 src
    displayName: 'Lint'
