# 1) CI sur branch1 uniquement
trigger:
  branches:
    include:
      - Branch_one
      - main

# 2) Validation PR vers main
pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest
    displayName: 'Install dependencies'
  - script: |
      pytest
    displayName: 'Run tests'
  - script: |
      python -m py_compile $(git ls-files '*.py')
    displayName: 'Build project'

