version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
  airflow:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: ["standalone"]
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"